-- Check if the columns exist and add them if they don't
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Password')
BEGIN
    ALTER TABLE Users ADD Password NVARCHAR(100) NULL;
    PRINT 'Added Password column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'PhoneNumber')
BEGIN
    ALTER TABLE Users ADD PhoneNumber NVARCHAR(50) NULL;
    PRINT 'Added PhoneNumber column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'WhatsAppNumber')
BEGIN
    ALTER TABLE Users ADD WhatsAppNumber NVARCHAR(50) NULL;
    PRINT 'Added WhatsAppNumber column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'StreetAddress')
BEGIN
    ALTER TABLE Users ADD StreetAddress NVARCHAR(100) NULL;
    PRINT 'Added StreetAddress column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'City')
BEGIN
    ALTER TABLE Users ADD City NVARCHAR(50) NULL;
    PRINT 'Added City column';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'ZipCode')
BEGIN
    ALTER TABLE Users ADD ZipCode NVARCHAR(20) NULL;
    PRINT 'Added ZipCode column';
END

-- Update constraints to allow NULL where needed
ALTER TABLE Users ALTER COLUMN Password NVARCHAR(100) NULL;
ALTER TABLE Users ALTER COLUMN PhoneNumber NVARCHAR(50) NULL;
ALTER TABLE Users ALTER COLUMN WhatsAppNumber NVARCHAR(50) NULL;
ALTER TABLE Users ALTER COLUMN StreetAddress NVARCHAR(100) NULL;
ALTER TABLE Users ALTER COLUMN City NVARCHAR(50) NULL;
ALTER TABLE Users ALTER COLUMN ZipCode NVARCHAR(20) NULL;

-- Print completion message
PRINT 'Users table updated successfully.'; 